{% set version = '1.1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-truncexpfam
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/TruncExpFam_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TruncExpFam/TruncExpFam_{{ version }}.tar.gz
  sha256: caf776f70573d65ae304749f5e821b7fe7c020095a8dccab82d7055cb6a3bb78

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-invgamma
    - r-rmutil
  run:
    - r-base
    - r-invgamma
    - r-rmutil

test:
  commands:
    - $R -e "library('TruncExpFam')"           # [not win]
    - "\"%R%\" -e \"library('TruncExpFam')\""  # [win]

about:
  home: https://ocbe-uio.github.io/TruncExpFam/
  dev_url: https://github.com/ocbe-uio/TruncExpFam
  license: GPL-3.0-only
  summary: Handles truncated members from the exponential family of probability distributions.
    Contains functions such as rtruncnorm() and dtruncpois(), which are truncated versions
    of rnorm() and dpois() from the stats package that also offer richer output containing,
    for example, the distribution parameters. It also provides functions to retrieve
    the original distribution parameters from a truncated sample by maximum-likelihood
    estimation.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: TruncExpFam
# Title: Truncated Exponential Family
# Version: 1.1.1
# Date: 2024-02-26
# Authors@R: c( person( given = "Rene", family = "Holst", role = "aut", email = "rene.holst@medisin.uio.no" ), person( given = "Waldir", family = "Leoncio", role = c("cre", "aut"), email = "w.l.netto@medisin.uio.no" ) )
# Description: Handles truncated members from the exponential family of probability distributions. Contains functions such as rtruncnorm() and dtruncpois(), which are truncated versions of rnorm() and dpois() from the stats package that also offer richer output containing, for example, the distribution parameters. It also provides functions to retrieve the original distribution parameters from a truncated sample by maximum-likelihood estimation.
# License: GPL-3
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Imports: methods, invgamma, rmutil
# Suggests: knitr, rmarkdown, testthat
# URL: https://ocbe-uio.github.io/TruncExpFam/
# BugReports: https://github.com/ocbe-uio/TruncExpFam/issues
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2024-02-26 15:11:48 UTC; waldir
# Author: Rene Holst [aut], Waldir Leoncio [cre, aut]
# Maintainer: Waldir Leoncio <w.l.netto@medisin.uio.no>
# Repository: CRAN
# Date/Publication: 2024-02-26 15:30:02 UTC
